### ISSUE TITLE
请问这个错误如何解决？

### ISSUE THREAD

**Issue by GL8666** [ChiChou/frida-ipa-dump#11]
YuzedeMacBook-Pro:frida-ipa-dump yuze$ ./dump.py TikTok
Traceback (most recent call last):
  File "./dump.py", line 13, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'

**Comment by GL8666** [comment]
frida-ps -U 是正常的

**Comment by ChiChou** [comment]
dump.py 默认使用 python3，你的 frida 可能装到 python2 的库去了。
改为 `python2 dump.py TikTok`

**Comment by ChiChou** [comment]
https://github.com/ChiChou/frida-ipa-dump/commit/d5b1daff6b67e810fe5baa1592e65ca85e2431ae
