### ISSUE TITLE
frida.TransportError: the connection is closed

### ISSUE THREAD

**Issue by ghost** [ChiChou/frida-ipa-dump#14]
按照方式配置环境，之后直接开始砸壳，设备连接正常。
bogon:frida-ipa-dump Bingo$ ./dump.py com.tencent.mqq
[info] attaching to target
Traceback (most recent call last):
  File "./dump.py", line 246, in <module>
    main()
  File "./dump.py", line 242, in main
    task.run()
  File "./dump.py", line 220, in run
    self.dump()
  File "./dump.py", line 136, in dump
    front = self.device.get_frontmost_application()
  File "/Library/Python/2.7/site-packages/frida/core.py", line 59, in get_frontmost_application
    return self._impl.get_frontmost_application()
frida.TransportError: the connection is closed

**Comment by nanhezzb** [comment]
> 按照方式配置环境，之后直接开始砸壳，设备连接正常。
> bogon:frida-ipa-dump Bingo$ ./dump.py com.tencent.mqq
> [info] attaching to target
> Traceback (most recent call last):
> File "./dump.py", line 246, in 
> main()
> File "./dump.py", line 242, in main
> task.run()
> File "./dump.py", line 220, in run
> self.dump()
> File "./dump.py", line 136, in dump
> front = self.device.get_frontmost_application()
> File "/Library/Python/2.7/site-packages/frida/core.py", line 59, in get_frontmost_application
> return self._impl.get_frontmost_application()
> frida.TransportError: the connection is closed

启动 app 之后执行命令报错为：
frida.ProcessNotRespondingError: expecting to read a single byte for receiving credentials but read zero bytes

**Comment by ChiChou** [comment]
frida 框架的bug，目前不知道原因
https://github.com/frida/frida/issues/543

**Comment by iamleetvin** [comment]
我看见the connection is closed就回一个我的回答，不过不知道是不是这个问题，我花了很长时间去解决
https://github.com/AloneMonkey/frida-ios-dump/issues/11#issuecomment-474232842

**Comment by ChiChou** [comment]
> 我看见the connection is closed就回一个我的回答，不过不知道是不是这个问题，我花了很长时间去解决
> [AloneMonkey/frida-ios-dump#11 (comment)](https://github.com/AloneMonkey/frida-ios-dump/issues/11#issuecomment-474232842)

本项目和 frida-ios-dump 的显著区别是这边不依赖 SSH，所以你遇到的问题不是同一个

**Comment by ChiChou** [comment]
@nanhezzb 目前 frida 仅支持 Electra。如果你使用 unc0ver 越狱，也会遇到这个错误。
