### ISSUE TITLE
砸出来一个zip.

### ISSUE THREAD

**Issue by yuzhouheike** [ChiChou/frida-ipa-dump#2]
1 手动修改为appname.app不能用!
2 手动修改为appname.app然后加到Payload文件夹.将Payload文件夹压缩成appname.ipa还是不能用

**Comment by yuzhouheike** [comment]
是不是很简单,怎么直接被关了

**Comment by ChiChou** [comment]
更新到最新版自动拼可直接 Impactor 安装的 ipa
