### ISSUE TITLE
Installation of ipa fails

### ISSUE THREAD

**Issue by queenofopera** [ChiChou/frida-ipa-dump#4]
Thank you very much for the tool.
After installation with impactor, I get the error
"installation.cpp:42 The WatchKit 2.0 app being installed contains an invalid application executable".

Any ideas?

**Comment by ChiChou** [comment]
Open .ipa as zip, delete directory `Payload/xxx.app/Watch`, save

**Comment by queenofopera** [comment]
![image](https://user-images.githubusercontent.com/39771679/40915664-95dd454a-6805-11e8-9728-c1df3bdd8739.png)

Which directory, please?
I'll update soon

**Comment by ChiChou** [comment]
I made a new commit to ignore WatchOS binaries.
Please use `git pull` to upgrade
