### ISSUE TITLE
frida.ProtocolError: unable to communicate with remote frida-server;

### ISSUE THREAD

**Issue by yuzhouheike** [ChiChou/frida-ipa-dump#6]
iOS11.3.1 提示版本不一致
frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
iOS10.1.1 没有问题
都是安装的12.0.5版本的frida插件

**Comment by ChiChou** [comment]
`pip install -U frida`
