### ISSUE TITLE
Dumping extensions

### ISSUE THREAD

**Issue by tosbaha** [ChiChou/frida-ipa-dump#9]
Hi,
I am trying to dump an ipa but it seems script doesn't decrypt extensions(Widgets, Push Notification Extensions etc) inside PlugIns folder. I will appreciate if you can add support for those. Thanks

**Comment by ChiChou** [comment]
Hello, can you give me an example app?

**Comment by tosbaha** [comment]
WordPress

**Comment by ChiChou** [comment]
@tosbaha Can you check the latest commit?

**Comment by ChiChou** [comment]
Tested WordPress, twitter, Gmail.
If any one have problem in dumping, please report the App name and bundle id.

**Comment by tosbaha** [comment]
Sorry for late reply and thanks for the update. Best regards.

**Comment by ChiChou** [comment]
Thanks for reporting the bug.
Here's the technical detail, if you're interested https://medium.com/0xcc/dump-ios-apps-in-javascript-part-i-f02ac4079e91
